config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'

  resources :projects, only: [ :index, :show ] do
    collection do
      get "top", to: "projects#top", as: :top
    end
    resources :investments, only: [ :new, :create ] do
      resources :payments, only: [:new, :create]
    end
    # resources :outputs, only: [ :new, :create ]
  end

  # sidekiq not sure it works
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: [ :show ] do
    resources :investments, only: [ :index, :show ]
  end

  get "learn_more", to: "pages#learn_more", as: :learn_more

  resources :leads, only: [ :new, :create ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # for API, not necessary at this point
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :outputs, only: [ :index, :show, :update, :create ]
    end
  end
end

app/models/investment.rb
class Investment < ApplicationRecord
  belongs_to :user
  belongs_to :project
  has_many :rents

  validates :number_of_panels, presence: true
  validates :state, presence: true, inclusion: { in: %w(pending confirmed) }

  monetize :amount_cents

  def income_per_year
    amount * project.yield
  end

  def last_month_gain
    last_month_outputs = project.outputs.where(:date => 1.months.ago..Date.today)
    outputs = last_month_outputs.group_by_day(:date).maximum(:quantity)
    day_value = 0
    outputs.each do |date, value|
      day_value += value * project.kwh_price_cents
    end
    day_value / 100
  end

  def last_month_outputs
    project.outputs.where(:date => 1.months.ago..Date.today)
    # kwh.where(:date => 1.months.ago..Date.today)
  end

  def kwc
    two_decimal_wc = project.panel_watt * number_of_panels / 10
    wc_int = two_decimal_wc.to_i
    wc_decimals = wc_int / 100.0
  end

  def share_of_total_power
    ( kwc * 100  / project.kwc) / 100.00
  end

  def watt

  end

  def kwh_lifetime
    kwc * 1200 * 25
  end

  def yield_in_integer
    yield_decimals = project.yield * 100
  end

  def past_gains
    (project.active_months * amount_cents * yield_in_integer.to_i / 100 / 12 / 100)
  end

  def remaining_gains
    (project.remaining_months / 12 * amount_cents * yield_in_integer.to_i / 100 / 100)
  end

  def total_gains
    remaining_gains + past_gains
  end

  def profits
    (total_gains * 100 - amount_cents) / 100
  end

  def co2_tonn_lifetime
    kwh = kwh_lifetime * 0.352 / 1000
    kwh_decimals = kwh * 100
    kwh_integer = kwh_decimals.to_i
    kwh_flote_one_decimal = kwh_integer / 100.0
  end

  def elephants_lifetime
    co2_tonn_lifetime / 6
  end
  def trees_lifetime
    co2_tonn_lifetime * 0.9
  end

  def km_car_lifetime
    co2_tonn_lifetime * 1000 / 0.18
  end

  def turns_world_lifetime
    km_car_lifetime / 40000
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :new ]

  def show
    @investment = Investment.find(params[:id])
    @project = @investment.project

    authorize @investment
  end

  def new
    @investment = Investment.new
    authorize @investment
    @project = Project.find(params[:project_id])
  end

  def create
    @investment = Investment.new(params_investment)
    authorize @investment
    @project = Project.find(params[:project_id])
    @investment.project = @project
    @investment.user = current_user
    @investment.state = "pending"

    if @investment.save!
      redirect_to new_project_investment_payment_path(@project, @investment)
    else
      render :new
    end
  end

  private

  def params_investment
    params.require(:investment).permit(:number_of_panels, :status)
  end

end

app/views/investments/_form.html.erb
<div class="investment-container-form">
  <%= simple_form_for(([ @project, investment]), method: :post, url: project_investments_path(@project))  do |f| %>
    <%= f.input :number_of_panels, label: "Choose your panels", placeholder: "e.g. 10", required: true, wrapper_html: { class: 'number-panels-form', id: 'number-panels-selected-investment'}%>

    <%= f.button :submit, "Invest now", class: "btn btn-main-green" %>
  <% end %>
</div>

app/views/investments/show.html.erb
<div class="container after-payment" id="js-cards-list">
  <div class="after-payment-header"><h1> Your payment is <%= @investment.state %>! </h1></div>
  <div class="after-payment-content">
    <div class="after-payment-content-introduction">
      <p>Congratulations, your investment is being processed. You will soon receive an email with all the details. We advice you to print this confirmation page as well.</p>
    </div>
    <table>
      <tbody>
        <tr>
          <td><h3>Project name:</h3></td>
          <td><p><%= @investment.project.name %> </p></td>
        </tr>
        <tr>
          <td><h3>Number of panels:</h3></td>
          <td><p><%= @investment.number_of_panels %> </p></td>
        </tr>
        <tr>
          <td><h3>Price per panel:</h3></td>
          <td><p> <%= humanized_money_with_symbol(@investment.project.price) %></p></td>
        </tr>
        <tr>
          <td><h3>Total amount:</h3></td>
          <td><span><p> <%= humanized_money_with_symbol(@investment.amount) %></p></span></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="after-payment-buttons">
    <%= link_to "Go to my dashboard", user_path(current_user), class:"btn-main-green"  %>
    <div class="btn-ancilliary">Print this page</div>
  </div>
</div>