config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'

  resources :projects, only: [ :index, :show ] do
    collection do
      get "top", to: "projects#top", as: :top
    end
    resources :investments, only: [ :new, :create ] do
      resources :payments, only: [:new, :create]
    end
    # resources :outputs, only: [ :new, :create ]
  end

  # sidekiq not sure it works
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: [ :show ] do
    resources :investments, only: [ :index, :show ]
  end

  get "learn_more", to: "pages#learn_more", as: :learn_more

  resources :leads, only: [ :new, :create ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # for API, not necessary at this point
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :outputs, only: [ :index, :show, :update, :create ]
    end
  end
end

app/views/shared/_card.html.erb
<%= link_to project_path(card), class: "card-projects" do %>
  <div class="card-header-projects text-left" style="background-image: linear-gradient(-535deg, rgba(0, 101, 168, 0) 0%, rgba(16, 28, 33, 0.63) 91%), url( <%= cl_image_path card.photo %>);">
    <div class="card-title-and-company-name">
      <h1> <%= card.name %> </h1>
      <h3> Hosted by <%= card.user.company_name %> </h3>
    </div>
    <%= cl_image_tag card.user.photo, class: "card-company-logo" %>
  </div>

 <div class="card-content">
    <div class="card-financial-details text-left">
      <div class="card__completion-rate-text">
        <strong><%= number_to_percentage(card.completion_rate, precision: 0)%></strong> funded
      </div>
      <progress  max="100" value="<%= card.completion_rate %>"> <%= card.completion_rate %> </progress>
      <div class="card__completion-rate-text">
        <%= card.status == "Completed" ? "Raised" : "Raising" %> <strong><%= humanized_money_with_symbol(card.total_cost) %></strong> !
      </div>
    </div>

    <div class="card-horizontal-line"></div>
    <div class="card-country-projects">
      <h2><%= card.status %> - <%= card.days_to_completion %></strong> days remaining</h2>
    </div>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <div class="footer">
    <p><%= link_to "Contact us", new_lead_path %></p>
    <p><%= link_to "Learn more", learn_more_path %></p>
    <div class="footer-copyright">
      &#9400;2018 Solarize Me
    </div>
  </div>

app/views/shared/_mailer.html.erb
<!-- <div class="mailer">

</div>
 -->

app/views/shared/_map.html.erb
<!-- code for map -->

app/views/shared/_navbar.html.erb
<div class="navbar-solarize" id="navbar">
  <!-- Logo -->
  <div class="navbar-solarize-logo-and-brand">
    <div class="navbar-solarize-logo">
      <%= icon("fas", "solar-panel") %>
    </div>
    <div class="navbar-solarize-brand">
      <%= link_to "SolarizeMe", root_path, class: "navbar-solarize-brand" %>
    </div>
  </div>

 <!-- Right Navigation -->
  <% current_page?(projects_path)? "active" : "" %>
  <div class="navbar-solarize-right hidden-xs hidden-sm">
    <%= link_to "All projects", projects_path, class: "navbar-solarize-item navbar-solarize-link #{current_page?(projects_path)? "active" : ""}", id: "navbar-all-projects" %>
    <!-- Dropdown list appearing on mobile onlyhidden-xs hidden-sm -->
    <% if user_signed_in? %>
      <%= link_to "My dashboard", user_path(current_user), class: "navbar-solarize-item navbar-solarize-link #{current_page?(user_path(current_user))? "active" : ""}", id: "navbar-dashboard"%>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <%= icon("fa", "sign-out-alt") %> <%= t(".sign_out", default: "Log out") %>
      <% end %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class:"navbar-solarize-item navbar-solarize-link" %>
    <% end %>
  </div>

  <!-- mobile only -->
  <div class="navbar-solarize-item hidden-md hidden-lg ">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-solarize-dropdown-menu">
        <li>
          <%= link_to "All projects", projects_path, class: "navbar-solarize-item navbar-solarize-link" %>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to "My dashboard", user_path(current_user), class: "navbar-solarize-item navbar-solarize-link" %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <%= icon("fa", "sign-out-alt") %> <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path, class:"navbar-solarize-item navbar-solarize-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>