config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'

  resources :projects, only: [ :index, :show ] do
    collection do
      get "top", to: "projects#top", as: :top
    end
    resources :investments, only: [ :new, :create ] do
      resources :payments, only: [:new, :create]
    end
    # resources :outputs, only: [ :new, :create ]
  end

  # sidekiq not sure it works
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: [ :show ] do
    resources :investments, only: [ :index, :show ]
  end

  get "learn_more", to: "pages#learn_more", as: :learn_more

  resources :leads, only: [ :new, :create ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # for API, not necessary at this point
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :outputs, only: [ :index, :show, :update, :create ]
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  before_action :set_investments

  def new
    @investment.amount_cents = @investment.project.price_cents * @investment.number_of_panels
    @investment.save!
  end

  def create
    customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
    )

  charge = Stripe::Charge.create(
    customer:     customer.id,   # You should store this customer id and re-use it.
    amount:       @investment.amount_cents.to_s,
    description:  "Payment for project #{@investment.project.name} for investment #{@investment.id}",
    currency:     @investment.amount.currency
  )

  @investment.update(payment: charge.to_json, state: 'confirmed')
  redirect_to user_investment_path(@investment.user, @investment)

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_project_investment_payment_path(@investment.project, @investment)
  end

  private

  def set_investments
    @investment = Investment.find(params[:investment_id])
    authorize @investment
  end
end

app/views/payments/new.html.erb
<div class="container payment" id="js-cards-list">
  <div class="payment-header"><h1>Investment confirmation</h1></div>
  <div class="payment-content">
    <div class="payment-content-project_name">
      <h3><%= icon("fas", "building") %> <%= @investment.project.name %></h3>
    </div>
    <hr>
    <div class="payment-content-sections">
      <div class="payment-content-sections_left-panel">
        <div class="payment-content-purchase">
          <div class="payment-content-purchase-icon">
            <%= image_tag "002-credit-card.svg", size: "80" %>
          </div>
          <div class="payment-content-purchase-infos">
            <p> <strong>Total amount due: <span><%= humanized_money_with_symbol(@investment.amount) %></span> </strong></p>
            <p> Your are purchasing  <%= pluralize(@investment.number_of_panels, "panel") %> </p>
            <p> Price per panel:  <%= humanized_money_with_symbol(@investment.project.price) %></p>
          </div>
        </div>
        <div class="payment-content-gains">
          <div class="payment-content-gains-icon">
            <%= image_tag "001-yield.svg", size: "80" %>
          </div>
          <div class="payment-content-gains-infos">
            <p><strong>Lifetime income: <span><%= humanized_money_with_symbol(@investment.total_gains) %></span> </strong>(approx)</p>
            <p>Income per year: <%= humanized_money_with_symbol(@investment.income_per_year) %> (approx)</p>
            <p>CO2 savings: <%= @investment.co2_tonn_lifetime %> tons </p>
            <p>Project duration: <%= @investment.project.duration_months / 12 %> years </p>
          </div>
        </div>
      </div>
    </div>
    <div class="payment-buttons">
      <%= link_to 'Back', :back, class: "btn btn-goback" %>
      <div class="payment-content-stripe">
        <%= form_tag project_investment_payments_path(@investment) do %>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-name="Project investment"
        data-email="<%= current_user.email %>"
        data-description="Project <%= @investment.project.name %>"
        data-amount="<%= @investment.amount_cents %>"
        data-currency="<%= @investment.amount.currency %>"></script>
        <script>
        // Hide default stripe button, be careful there if you
        // have more than 1 button of that class
        document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';
      </script>
      <button type="submit" class="btn-main-green">Invest now</button>
      <% end %>
    </div>
  </div>
</div>
</div>